apiVersion: build.pivotal.io/v1alpha1
kind: Image
metadata:
  name: confirmation-service
  namespace: kpack
spec:
  tag: dhubau/confirmation-service
  serviceAccount: kpack-service-account
  successBuildHistoryLimit: 2
  builder:
    name: default-builder
    kind: Builder
  cacheSize: "2Gi"
  source:
    git:
      url: https://github.com/mshahat/tanzu-demo.git
      revision: master
    subPath: "confirmation-service"