apiVersion: build.pivotal.io/v1alpha1
kind: Image
metadata:
  name: symfony-demo-app
  namespace: kpack
spec:
  tag: mshahat/symfony-demo-app
  serviceAccount: kpack-service-account
  successBuildHistoryLimit: 2
  builder:
    name: php-builder
    kind: CustomBuilder
  cacheSize: "2Gi"
  source:
    git:
      url: https://github.com/mshahat/php-symfony-demo.git
      revision: master
  build:
    env:
      - name: "APP_ENV"
        value: "prod"