apiVersion: v1
kind: ServiceAccount
metadata:
  name: kpack-service-account
  namespace: kpack
secrets:
  - name: dockerhub-creds
  - name: github-creds
---
apiVersion: kpack.io/v1alpha1
kind: Builder
metadata:
  name: default-builder
  namespace: kpack
spec:
  tag: mshahat/javabuilder
  serviceAccount: kpack-service-account
  stack: 
    name: base
    kind: ClusterStack
  store: 
    name: sample-cluster-store
    kind: ClusterStore
  order:
  - group:
    - id: paketo-buildpacks/java
